import { UserRole } from "../generated/prisma/client.js";

export const permissionGroups = {
  user: [
    "user.read",
    "user.create",
    "user.update",
    "user.archive",
    "user.restore",
    "user.import",
    "user.reset_password",
  ],
  permission: [
    "permission.read",
    "permission.manage",
    "role.read",
    "role.manage",
  ],
  birdep: ["birdep.read.all", "birdep.update.own", "birdep.update.all"],
  member: [
    "member.read.all",
    "member.create.own_birdep",
    "member.update.own_birdep",
    "member.archive.own_birdep",
    "member.photo.update.own_birdep",
    "member.manage.all",
  ],
  program: [
    "program.read.all",
    "program.create.own_birdep",
    "program.update.own_birdep",
    "program.archive.own_birdep",
    "program.restore.own_birdep",
    "program.update.collaboration",
    "program.manage.all",
  ],
  progress: [
    "progress.read.all",
    "progress.create.own_birdep",
    "progress.update.own_birdep",
  ],
  pressRelease: [
    "press_release.read.all",
    "press_release.create.own_birdep",
    "press_release.update.own_birdep",
    "press_release.archive.own_birdep",
  ],
  tevoCms: [
    "tevo.landing.manage",
    "tevo.about.manage",
    "tevo.structure.manage",
    "tevo.member.manage",
    "tevo.birdep.manage",
    "tevo.program.manage",
    "tevo.news.manage",
    "tevo.media.manage",
    "tevo.content.submit_review",
  ],
  tevoApproval: [
    "tevo.approval.review",
    "tevo.approval.approve",
    "tevo.approval.reject",
    "tevo.approval.reassign",
  ],
  audit: ["audit.read.all", "audit.read.own_birdep"],
  import: [
    "import.members",
    "import.birdeps",
    "import.press_releases",
  ],
} as const;

export const permissions = Object.entries(permissionGroups).flatMap(
  ([group, codes]) =>
    codes.map((code) => ({
      code,
      group,
      description: code,
    })),
);

export const roleTemplates = [
  {
    code: UserRole.SUPER_ADMIN,
    name: "Super Admin",
    description: "Akses penuh untuk konfigurasi Nexus dan Tevo.",
    permissions: permissions.map((permission) => permission.code),
  },
  {
    code: UserRole.BPH,
    name: "BPH",
    description: "Reviewer dan pemantau lintas Birdep.",
    permissions: [
      "birdep.read.all",
      "birdep.update.all",
      "member.read.all",
      "program.read.all",
      "program.manage.all",
      "progress.read.all",
      "press_release.read.all",
      "tevo.approval.review",
      "tevo.approval.approve",
      "tevo.approval.reject",
      "audit.read.all",
    ],
  },
  {
    code: UserRole.TEVO_ADMIN,
    name: "Tevo Admin",
    description: "Pengelola konten publik Tevo sampai tahap review.",
    permissions: [
      "tevo.landing.manage",
      "tevo.about.manage",
      "tevo.structure.manage",
      "tevo.member.manage",
      "tevo.birdep.manage",
      "tevo.program.manage",
      "tevo.news.manage",
      "tevo.media.manage",
      "tevo.content.submit_review",
    ],
  },
  {
    code: UserRole.KETUA_BIRDEP,
    name: "Ketua Birdep",
    description: "Mengelola data dan program kerja Birdep sendiri.",
    permissions: [
      "birdep.read.all",
      "birdep.update.own",
      "member.read.all",
      "member.create.own_birdep",
      "member.update.own_birdep",
      "member.archive.own_birdep",
      "member.photo.update.own_birdep",
      "program.read.all",
      "program.create.own_birdep",
      "program.update.own_birdep",
      "program.archive.own_birdep",
      "program.restore.own_birdep",
      "program.update.collaboration",
      "progress.read.all",
      "progress.create.own_birdep",
      "progress.update.own_birdep",
      "press_release.read.all",
      "press_release.create.own_birdep",
      "press_release.update.own_birdep",
      "press_release.archive.own_birdep",
      "audit.read.own_birdep",
    ],
  },
  {
    code: UserRole.SEKRETARIS_BIRDEP,
    name: "Sekretaris Birdep",
    description: "Membantu administrasi anggota dan program Birdep.",
    permissions: [
      "birdep.read.all",
      "member.read.all",
      "member.update.own_birdep",
      "program.read.all",
      "program.update.own_birdep",
      "progress.read.all",
      "progress.create.own_birdep",
      "press_release.read.all",
      "press_release.create.own_birdep",
    ],
  },
  {
    code: UserRole.BENDAHARA_BIRDEP,
    name: "Bendahara Birdep",
    description: "Melihat program dan membuat pembaruan unit sendiri.",
    permissions: [
      "birdep.read.all",
      "member.read.all",
      "program.read.all",
      "program.update.own_birdep",
      "progress.read.all",
      "progress.create.own_birdep",
    ],
  },
  {
    code: UserRole.ANGGOTA_BIRDEP,
    name: "Anggota Birdep",
    description: "Akses baca ringkasan organisasi dan program.",
    permissions: [
      "birdep.read.all",
      "member.read.all",
      "program.read.all",
      "progress.read.all",
      "press_release.read.all",
    ],
  },
] as const;
