import { UserRole } from "../generated/prisma/client.js";

export const permissionGroups = {
  nexus: ["nexus.read.basic", "nexus.read.all"],
  news: [
    "news.read",
    "news.create",
    "news.update.all",
    "news.delete.all",
    "news.manage.all",
  ],
  program: [
    "program.read.summary",
    "program.read.own_detail",
    "program.read.all_detail",
    "program.create.own_birdep",
    "program.update.own_progress",
    "program.upload.own_progress_asset",
    "program.update.own_birdep",
    "program.archive.own_birdep",
    "program.restore.own_birdep",
    "program.update.collaboration",
    "program.manage.all",
  ],
  user: [
    "user.read",
    "user.create",
    "user.update",
    "user.delete",
    "user.archive",
    "user.restore",
    "user.import",
    "user.reset_password",
  ],
  role: ["role.read", "role.manage", "role.assign", "role.revoke"],
  permission: ["permission.read", "permission.manage"],
  birdep: ["birdep.read.all", "birdep.update.own", "birdep.update.all"],
  member: [
    "member.read.all",
    "member.create.own_birdep",
    "member.update.own_birdep",
    "member.archive.own_birdep",
    "member.photo.update.own_birdep",
    "member.manage.all",
  ],
  progress: [
    "progress.read.all",
    "progress.create.own_birdep",
    "progress.update.own_birdep",
  ],
  pressRelease: [
    "press_release.read.all",
    "press_release.create.own_birdep",
    "press_release.update.own_birdep",
    "press_release.archive.own_birdep",
  ],
  cms: [
    "cms.read",
    "cms.create",
    "cms.update",
    "cms.upload",
    "cms.publish",
    "cms.manage.all",
    "tevo.landing.manage",
    "tevo.about.manage",
    "tevo.structure.manage",
    "tevo.member.manage",
    "tevo.birdep.manage",
    "tevo.program.manage",
    "tevo.news.manage",
    "tevo.media.manage",
    "tevo.content.submit_review",
  ],
  tevoApproval: [
    "tevo.approval.review",
    "tevo.approval.approve",
    "tevo.approval.reject",
    "tevo.approval.reassign",
  ],
  audit: ["audit.read", "audit.read.all", "audit.read.own_birdep"],
  import: [
    "import.manage",
    "import.members",
    "import.birdeps",
    "import.press_releases",
  ],
} as const;

export const permissions = Object.entries(permissionGroups).flatMap(
  ([group, codes]) =>
    codes.map((code) => ({
      code,
      group,
      description: code,
    })),
);

const allPermissions = permissions.map((permission) => permission.code);

export const roleTemplates = [
  {
    code: UserRole.LAKSANA,
    name: "Laksana",
    description: "Akses dasar Nexus dan progres program ringkas.",
    permissions: ["nexus.read.basic", "news.read", "program.read.summary"],
  },
  {
    code: UserRole.KSATRIA,
    name: "Ksatria",
    description: "Akses dasar serta update progres program Birdep sendiri.",
    permissions: [
      "nexus.read.basic",
      "news.read",
      "program.read.summary",
      "program.read.own_detail",
      "program.update.own_progress",
      "program.upload.own_progress_asset",
      "progress.create.own_birdep",
      "progress.update.own_birdep",
    ],
  },
  {
    code: UserRole.BPH,
    name: "BPH",
    description: "Monitoring seluruh progres dan pembuat news.",
    permissions: [
      "nexus.read.basic",
      "news.read",
      "news.create",
      "program.read.summary",
      "program.read.all_detail",
      "progress.read.all",
      "press_release.read.all",
      "tevo.approval.review",
      "tevo.approval.approve",
      "tevo.approval.reject",
      "audit.read.own_birdep",
    ],
  },
  {
    code: UserRole.ADMIN,
    name: "Admin",
    description: "Pengelola data operasional, news, dan CMS TEVO.",
    permissions: [
      "nexus.read.all",
      "news.read",
      "news.create",
      "news.update.all",
      "news.delete.all",
      "program.read.all_detail",
      "cms.read",
      "cms.create",
      "cms.update",
      "cms.upload",
      "cms.publish",
      "tevo.landing.manage",
      "tevo.about.manage",
      "tevo.structure.manage",
      "tevo.member.manage",
      "tevo.birdep.manage",
      "tevo.program.manage",
      "tevo.news.manage",
      "tevo.media.manage",
      "tevo.content.submit_review",
    ],
  },
  {
    code: UserRole.SUPER_ADMIN,
    name: "Super Admin",
    description: "Akses tertinggi untuk semua modul Nexus dan TEVO.",
    permissions: allPermissions,
  },
  {
    code: UserRole.TEVO_ADMIN,
    name: "Tevo Admin",
    description: "Alias kompatibilitas untuk pengelola konten publik TEVO.",
    permissions: [
      "cms.read",
      "cms.create",
      "cms.update",
      "cms.upload",
      "cms.publish",
      "tevo.landing.manage",
      "tevo.about.manage",
      "tevo.structure.manage",
      "tevo.member.manage",
      "tevo.birdep.manage",
      "tevo.program.manage",
      "tevo.news.manage",
      "tevo.media.manage",
      "tevo.content.submit_review",
    ],
  },
  {
    code: UserRole.KETUA_BIRDEP,
    name: "Ketua Birdep",
    description: "Alias kompatibilitas untuk pengelola Birdep sendiri.",
    permissions: [
      "nexus.read.basic",
      "news.read",
      "program.read.summary",
      "program.read.own_detail",
      "program.create.own_birdep",
      "program.update.own_progress",
      "program.update.own_birdep",
      "program.archive.own_birdep",
      "program.restore.own_birdep",
      "member.read.all",
      "member.create.own_birdep",
      "member.update.own_birdep",
      "audit.read.own_birdep",
    ],
  },
  {
    code: UserRole.SEKRETARIS_BIRDEP,
    name: "Sekretaris Birdep",
    description: "Alias kompatibilitas untuk administrasi Birdep.",
    permissions: [
      "nexus.read.basic",
      "news.read",
      "program.read.summary",
      "program.read.own_detail",
      "program.update.own_progress",
      "member.read.all",
      "member.update.own_birdep",
    ],
  },
  {
    code: UserRole.BENDAHARA_BIRDEP,
    name: "Bendahara Birdep",
    description: "Alias kompatibilitas untuk akses ringkas Birdep.",
    permissions: [
      "nexus.read.basic",
      "news.read",
      "program.read.summary",
      "program.read.own_detail",
    ],
  },
  {
    code: UserRole.ANGGOTA_BIRDEP,
    name: "Anggota Birdep",
    description: "Alias kompatibilitas untuk akses dasar.",
    permissions: ["nexus.read.basic", "news.read", "program.read.summary"],
  },
] as const;
